spring.application.name=seguros-app

spring.datasource.url=jdbc:postgresql://localhost:5432/insurance_db
spring.datasource.username=postgres
spring.datasource.password=CHANGE_ME

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true

# CONFIGURACIÓN EMAIL

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=aseguradoraapp@gmail.com
spring.mail.password=CHANGE_ME

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true