package com.seguros.app.util;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.seguros.app.model.Payment;
import java.io.OutputStream;
import java.util.List;

public class PaymentReportPdfGenerator {

    public static void generate(List<Payment> payments,
                                OutputStream outputStream) throws Exception {

        // Crea el documento PDF en orientación horizontal
        Document document = new Document(PageSize.A4.rotate(), 36, 36, 50, 36);

        // Asocia el documento con el flujo de salida
        PdfWriter.getInstance(document, outputStream);

        // Abre el documento para comenzar a escribir
        document.open();

        // Configura la fuente del título
        Font titleFont = new Font(Font.HELVETICA, 20, Font.BOLD);

        // Crea el título del reporte
        Paragraph title = new Paragraph("Payments Report", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        // Agrega un espacio en blanco
        document.add(new Paragraph(" "));

        // Crea una tabla con 6 columnas
        PdfPTable table = new PdfPTable(6);
        table.setWidthPercentage(100);

        // Agrega los encabezados de la tabla
        table.addCell(createHeaderCell("Date"));
        table.addCell(createHeaderCell("Client"));
        table.addCell(createHeaderCell("Policy"));
        table.addCell(createHeaderCell("Method"));
        table.addCell(createHeaderCell("Installments"));
        table.addCell(createHeaderCell("Amount"));

        // Variable para acumular el total recaudado
        double total = 0;

        // Recorre todos los pagos y los agrega a la tabla
        for (Payment payment : payments) {

            // Agrega la fecha del pago
            table.addCell(String.valueOf(payment.getPaymentDate()));

            // Agrega el nombre del cliente
            table.addCell(
                    payment.getPolicy()
                           .getClient()
                           .getName()
            );

            // Agrega el número de póliza
            table.addCell(
                    payment.getPolicy()
                           .getPolicyNumber()
            );

            // Agrega el método de pago
            table.addCell(payment.getPaymentMethod());

            // Agrega el número de cuotas
            table.addCell(
                    String.valueOf(payment.getInstallments())
            );

            // Agrega el monto del pago
            table.addCell(
                    String.format("%,.2f", payment.getAmount())
            );

            // Suma el monto al total general
            total += payment.getAmount();
        }

        // Agrega la tabla al documento
        document.add(table);

        // Agrega un espacio en blanco
        document.add(new Paragraph(" "));

        // Crea el párrafo con el total recaudado
        Paragraph totalParagraph = new Paragraph(
                "Total Revenue: " + String.format("%,.2f", total)
        );

        // Alinea el total a la derecha
        totalParagraph.setAlignment(Element.ALIGN_RIGHT);

        // Agrega el total al documento
        document.add(totalParagraph);

        // Agrega un espacio en blanco
        document.add(new Paragraph(" "));

        // Crea el mensaje final del reporte
        Paragraph footer = new Paragraph(
                "Generated by Seguros App"
        );

        // Centra el mensaje final
        footer.setAlignment(Element.ALIGN_CENTER);

        // Agrega el mensaje al documento
        document.add(footer);

        // Cierra el documento PDF
        document.close();
    }

    private static PdfPCell createHeaderCell(String text) {

        // Crea una celda con el texto indicado
        PdfPCell cell = new PdfPCell(new Phrase(text));

        // Agrega espacio interno a la celda
        cell.setPadding(6);

        // Centra el texto horizontalmente
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);

        return cell;
    }
}